name: Library

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install linux packages
        run: |
          cat /etc/issue
          sudo apt-get update
          sudo apt-get -yqq install libmysqlclient-dev

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install pipenv
          touch Pipfile & pipenv install --deploy --dev
          if [ -f requirements.txt ]; then pipenv install -r requirements.txt; fi

      - name: Install locally
        run: |
          pipenv run pip install -e .

      - name: Test with pytest
        run: |
          pipenv run python -m pytest -s --verbosity=3
          echo Done!
