name: Notebooks

on:
  push:
    branches: [ master ]
    paths:
      - 'notebooks/**'
      - '!notebooks/README.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'notebooks/**'
      - '!notebooks/README.md'
  workflow_run:
    workflows: [ "Library" ]
    branches: [ master ]
    types:
      - completed

  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install linux packages
        run: |
          cat /etc/issue
          sudo apt-get update
          sudo apt-get -yqq install libmysqlclient-dev

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install pipenv
          touch Pipfile & pipenv install --deploy --dev
          if [ -f requirements.txt ]; then pipenv install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          sed -ie "s|project_name='.*'|project_name='testrepo'|" notebooks/PatternsTest.ipynb
          PYTHONPATH=`pwd`/src pipenv run pytest -s --verbosity=3 notebooks
          echo Done!
